CREATE DATABASE IF NOT EXISTS springtest  DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;

USE springtest;

CREATE TABLE IF NOT EXISTS `Users`(
`id` INT(8) NOT NULL AUTO_INCREMENT,
`name` VARCHAR(30) NOT NULL ,
`password` VARCHAR(20) NOT NULL ,
`salt` CHAR(36) NOT NULL,
`sex` VARCHAR(2) NOT NULL COMMENT'性别',
`birthday` DATETIME DEFAULT NULL COMMENT '出生日期',
`createtime` DATETIME DEFAULT NOW(),
`updatetime` DATETIME DEFAULT NOW(),
`address`VARCHAR (100)DEFAULT NULL COMMENT '家庭住址',
`email`VARCHAR(50)DEFAULT NULL COMMENT '邮箱',
-- 添加主键操作
PRIMARY KEY (`id`)
)ENGINE=INNODB;